### ISSUE TITLE
Access Analysis + Subsetting

### ISSUE THREAD

**Issue by wyman10** [ualbertalib/dvn#16]
When I try to go to Access Analysis + Subsetting from the Data & Analysis tab dataverse hangs.

The study I am using is http://dx.doi.org/10.7939/DVN/10011

**Comment by piyapongch** [comment]
I have tried it and it's working. Please try again. I think it might be memory problem. The server has been restarted. Everything should be working now.

**Comment by wyman10** [comment]
Looks Good - Thanks
