### ISSUE TITLE
Public access account creation email problem

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/dvn#17]
The send mail failure email has been sent to my mailbox instead of data@ualberta.ca. The public account request form has been created using my account. The form need to be moved to data@ualberta.ca account instead.

**Comment by piyapongch** [comment]
Will be replaced with authentication module including Shibboleth integration in Dataverse 4.0.

**Comment by pdurbin** [comment]
Yes! So far [Shibboleth](https://docs.google.com/document/d/12Qru8Gjq4oDUiodI00oObHJog65S7QzFfFZuPU3n8aU/edit?usp=sharing) seems to be working ok in 4.0!

I'd be curious to hear more about this authentication module.
