### ISSUE TITLE
"Download the cataloging information in XML format" function

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dvn#20]
This function does not seem to be working at the moment. The function will likely be required to support the export of metadata to be ingested into Hydra North prior to its launch. Can this be easily remedied? Thanks

**Comment by sfarnel** [comment]
I tried this out with one of the studies in the Thom Hess Collection in the UA Dataverse:
http://dx.doi.org/10.7939/DVN/10137 

When I click on Download catalog info I'm taken to the following URL:

https://dataverse.library.ualberta.ca:80/dvn/api/metadata/87

which is a blank page. Trying save file as gives a server error.

I think this has to do with the port (80) being in the URL. If I try the following URL (without the port)

https://dataverse.library.ualberta.ca/dvn/api/metadata/87

I get a DDI file in XML which I can view in the browser or download. (The XML is a little on the wonky side though so we may want to look at it a little more closely).

Over to the experts to dig further!

**Comment by pcharoen** [comment]
I've got the same problem. It's working fine on Hibernian, development
server. Even though, it also has :80 at the end of domain name. I think
might be something on the web server configuration. I've submitted a ticket
to Henry. He will take care of the problem.

Piyapong.

**Comment by piyapongch** [comment]
You can also export all items from the Utilities tab on the admin interface. The metadata will be on the server. Let me know if you want to do that. I can work with Henry to get them for you.

**Comment by piyapongch** [comment]
You can get Dataverse's metadata in oai_dc, ddi and marc format.

**Comment by johnhuck** [comment]
Thanks, both. This gives me a couple of avenues to follow. My first issue submitted on github and a speedy response!

**Comment by piyapongch** [comment]
I've exported all items on Dataverse. They're now on the server. Henry will collect them and give to me later this week. I'll then give them to you. Just in case, you want to investigate in other item.

**Comment by sfarnel** [comment]
Thanks Piyapong.

On Tue, Mar 3, 2015 at 10:13 AM, Piyapong Charoenwattana <
notifications@github.com> wrote:

> I've exported all items on Dataverse. They're now on the server. Henry
> will collect them and give to me later this week. I'll then give them to
> you. Just in case, you want to investigate in other item.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ualbertalib/dvn/issues/20#issuecomment-76988983.

## 

Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Sharon, I think the wonkiness is only in the embedded html, where every
opening angle bracket has been escaped (to prevent it being interpreted as
an xml element). If I open it in Oxygen and hit ctrl-I to reformat, it
looks ok, though there are a couple of validation errors for DVN-specific
values that presumably aren't in the DDI schema. Does that match your
experience?

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfarnel** [comment]
Thanks Peter. After playing a bit, you're right; the weirdness was fixed
with reformatting. And the validity problems are with the DVN specific
info. I see that other Dataverse instances have different versions of DDI
available for download. Something for future consideration.

On Tue, Mar 3, 2015 at 5:10 PM, Peter Binkley notifications@github.com
wrote:

> Sharon, I think the wonkiness is only in the embedded html, where every
> opening angle bracket has been escaped (to prevent it being interpreted as
> an xml element). If I open it in Oxygen and hit ctrl-I to reformat, it
> looks ok, though there are a couple of validation errors for DVN-specific
> values that presumably aren't in the DDI schema. Does that match your
> experience?
> 
> Peter
> 
> Peter Binkley
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
> 
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
> 
> phone 780-492-3743
> fax 780-492-9243
> 
> On 2 March 2015 at 21:16, Sharon Farnel notifications@github.com wrote:
> 
> > I tried this out with one of the studies in the Thom Hess Collection in
> > the UA Dataverse:
> > http://dx.doi.org/10.7939/DVN/10137
> > 
> > When I click on Download catalog info I'm taken to the following URL:
> > 
> > https://dataverse.library.ualberta.ca:80/dvn/api/metadata/87
> > 
> > which is a blank page. Trying save file as gives a server error.
> > 
> > I think this has to do with the port (80) being in the URL. If I try the
> > following URL (without the port)
> > 
> > https://dataverse.library.ualberta.ca/dvn/api/metadata/87
> > 
> > I get a DDI file in XML which I can view in the browser or download. (The
> > XML is a little on the wonky side though so we may want to look at it a
> > little more closely).
> > 
> > Over to the experts to dig further!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ualbertalib/dvn/issues/20#issuecomment-76884524.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ualbertalib/dvn/issues/20#issuecomment-77068989.

## 

Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by piyapongch** [comment]
I think I've found how to fix the metadata download broken link. I'm going to try this morning.

**Comment by piyapongch** [comment]
I've fixed the problem and redeployed the application on the production server. The feature is now working properly.

**Comment by johnhuck** [comment]
Thanks, Piyapong!
