### ISSUE TITLE
Download bundle excessed the limit of 104857600 bytes.

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/dvn#21]
From: llaliber@ualberta.ca Larry Laliberte 
To:  
Date: Fri, 13 Mar 2015 11:22:46 -0600 
Subject: Re: [Ticket#201409221011951] Ticket owner assigned to you! (Dataverse CCID login pro [...]) 

I tried downloading all of the files located here:
https://dataverse.library.ualberta.ca/dvn/dv/3m1i/faces/study/StudyPage.xhtml?globalId=doi:10.7939/DVN/10242&studyListingIndex=0_41d24796d690c74379d19e3634b4

They are well under the 1GB that we had set back in September but I am
still only getting 2 of the three datasets and the following MANIFEST.TXT
message

S_265_1920_clip.zip (application/zip) 51825272 bytes.
S_265_1920_lines.dbf (application/octet-stream) 4402962 bytes.
S_265_1920_lines.prj (text/plain; charset=US-ASCII) 428 bytes.
S_265_1920_lines.sbn (application/octet-stream) 2832292 bytes.
S_265_1920_lines.sbx (application/octet-stream) 189844 bytes.
S_265_1920_lines.shp (application/octet-stream) 55838524 bytes.
S_265_1920_lines.shx skipped because the total size of the download bundle
exceeded the limit of 104857600 bytes.
N029929.TIF skipped because the total size of the download bundle exceeded
the limit of 104857600 bytes.

All the best
Larry

On Tue, Sep 23, 2014 at 1:12 PM, Guanwen Zhang guanwen@ualberta.ca wrote:

> Hi Chuck,
> 
> Is it OK for me to copy the DVN-web.war from hibernian to dataverse now?
> Because the configuration file needs to be changed, I need to stop and
> restart the glassfish web server.
> The download time is about 5 minutes if everything goes well
> 
> regards
> Henry
> 
> On Tue, Sep 23, 2014 at 12:51 PM, Piyapong Charoenwattana <
> piyapong.charoenwattana@ualberta.ca> wrote:
> 
> > I have also tried with public account and it is working properly. I think
> > think the problem has been fixed. I will give to Henry to deploy it on the
> > production server.
> > 
> > Henry:
> > 
> > Can you deploy the application to the production server? You can get the
> > DVN-web.war from hibernian. Beside the bug fix, I have added maximum bundle
> > download size to 1 GB. You need to add the jvm-options in domain.xml. Here
> > is the configuration:
> > 
> > <jvm-options>-Ddvn.batchdownload.limit=1073741824</jvm-options>
> > 
> > You can see it in domain.xml on hibernian.
> > 
> > Thanks,
> > 
> > Piyapong.
> > 
> > On Tue, Sep 23, 2014 at 12:39 PM, Chuck Humphrey <
> > chuck.humphrey@ualberta.ca> wrote:
> > 
> > > Thanks, Piyapong.  I was able to register on the development version
> > > using my CCID.  Chuck
> > > 
> > > On Tue, Sep 23, 2014 at 12:11 PM, Piyapong Charoenwattana <
> > > piyapong.charoenwattana@ualberta.ca> wrote:
> > > 
> > > > I have found a bug and I have fixed it. The fix has been applied to the
> > > > development server. You can try it at
> > > > https://hibernian.library.ualberta.ca/dvn/.
> > > > 
> > > > If you want to use your CCID to try, please let me know. I will need to
> > > > delete your account, dataverse and studies.
> > > > 
> > > > Thanks,
> > > > 
> > > > Piyapong.
> > > > 
> > > > On Tue, Sep 23, 2014 at 9:53 AM, Guanwen Zhang guanwen@ualberta.ca
> > > > wrote:
> > > > 
> > > > > use  "/etc/init.d/postgresql restart" to restart
> > > > > 
> > > > > After you restart postgresql server, you need to restart glassfish
> > > > > 
> > > > > service glassfish stop
> > > > > service glassfish start
> > > > > 
> > > > > On Tue, Sep 23, 2014 at 9:46 AM, Piyapong Charoenwattana <
> > > > > piyapong.charoenwattana@ualberta.ca> wrote:
> > > > > 
> > > > > > I have made some change to pg_hba.conf on hibernian, but it did not
> > > > > > work. Can you take a look? I am trying to use pgAdmin GUI client to access
> > > > > > the database from my workstation.
> > > > > > 
> > > > > > What is a command to restart the PostgreSQL server?
> > > > > > 
> > > > > > Thanks,
> > > > > > 
> > > > > > Piyapong.
> > > > > > 
> > > > > > On Tue, Sep 23, 2014 at 9:39 AM, Piyapong Charoenwattana <
> > > > > > piyapong.charoenwattana@ualberta.ca> wrote:
> > > > > > 
> > > > > > > Henry:
> > > > > > > 
> > > > > > > Can you grant access to PostgreSQL on Hibernain and give me log
> > > > > > > files from Dataverse production server? I will need to investigate the
> > > > > > > problem.
> > > > > > > 
> > > > > > > Thanks,
> > > > > > > 
> > > > > > > Piyapong.
> > > > > > > 
> > > > > > > On Mon, Sep 22, 2014 at 3:55 PM, UofA Libraries Help Desk
> > > > > > > Notification libraryhelpdesk@ualberta.ca wrote:
> > > > > > > 
> > > > > > > > Hi Piyapong,
> > > > > > > > 
> > > > > > > > Ticket [201409221011951] is assigned to you by Wendy Cheng.
> > > > > > > > 
> > > > > > > > Comment:
> > > > > > > > 
> > > > > > > > I have spoken to Pyapong about a problem reported by two
> > > > > > > > individuals who had
> > > > > > > > never registered with Dataverse prior to today who are told that
> > > > > > > > their login
> > > > > > > > failed. To help isolate the problem, I asked one of them to verify
> > > > > > > > their
> > > > > > > > CCID/pwd at  [1]https://myccid.ualberta.ca/check. She got a green
> > > > > > > > check mark
> > > > > > > > indicating a valid CCID and pwd.  Next, I asked her to send us a
> > > > > > > > screen shot
> > > > > > > > of the error message.  This is pasted below.
> > > > > > > > 
> > > > > > > > I have spoken with Pyapong about this so he is expecting the help
> > > > > > > > desk to be
> > > > > > > > directed to him.
> > > > > > > > 
> > > > > > > > Thanks, Chuck
> > > > > > > > 
> > > > > > > > [1] https://myccid.ualberta.ca/check
> > > > > > > > 
> > > > > > > > https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentZoom;TicketID=11952
> > > > > > > > 
> > > > > > > > UofA Libraries Help Desk

**Comment by henryzhang87** [comment]
I checked on the production machine about the version of DVN-web.war, it
said Sept 23. 2014, that means on September 23, 2014,
the war file was deployed.

To fix the batch download maximum, we needs to change in domain.xml which
is outside of DVN-web.war.

regards

Henry

**Comment by henryzhang87** [comment]
Last deployment time for DVN-web.war

drwxr-xr-x. 2 root root     4096 Feb 13  2012 bundles
-rw-r--r--. 1 root root 38141636 Sep 23 13:21 DVN-web.war
-rw-r--r--. 1 root root        0 Sep 23 14:15 DVN-web.war_deployed

**Comment by piyapongch** [comment]
Henry has applied the file size configuration on domain.xml.
