### ISSUE TITLE
Fixing minor grammatical errors on landing page text.

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dvn#24]
https://dataverse.library.ualberta.ca/dvn/

In the sentence "This services is provided to help researchers to publish, analyze, distribute and preserve their data and datasets,"

"services" should be "service," and

 "to" should not be repeated after "researchers". 

"This service is provided to help researchers publish, analyze, distribute and preserve their data and datasets."

**Comment by piyapongch** [comment]
I have changed the message.
