### ISSUE TITLE
Diacritics issue in the variable names for TAB files

### ISSUE THREAD

**Issue by wyman10** [ualbertalib/dvn#26]
We recently tried to import a SPSS file to generate a TAB file in Dataverse so that we can try out the analysis/sub setting features. However, the field variable names that are in French did not import correctly (another diacritics issue?) – the data file is in the Canadian Century Research Infrastructure Dataverse under the CCRI 1911 Census of Canada Aggregate Data and Geography study and the file is called ccri_pub_1911_v2t2.tab

**Comment by piyapongch** [comment]
Can you give me the study URL? Thanks,

**Comment by wyman10** [comment]
https://dataverse.library.ualberta.ca/dvn/dv/CCRI/faces/study/StudyPage.xhtml?globalId=doi:10.7939/DVN/10269&versionNumber=1

and it is TAB file ccri_pub_1911_v2t2.tab

**Comment by piyapongch** [comment]
Can you give me the original file? Thanks,

**Comment by wyman10** [comment]
here you go...

**Comment by piyapongch** [comment]
I could not get it. Can you send again by attaching to your email?

I have found an issue, https://github.com/IQSS/dataverse/issues/1343/. It
have never got to the production for v3. I have tried v4.0 at
https://dataverse-demo.iq.harvard.edu. They have implemented the feature. I
have added a file and the advanced options showed up and I can select
character encoding.

Piyapong.

**Comment by wyman10** [comment]
I have attached the unzipped .sav file

**Comment by johnhuck** [comment]
Can you try the file with v4.0 at dataverse devo site,
https://dataverse-demo.iq.harvard.edu/? I will show a advanced options
button after you uploaded and you can select character encoding. If it that
work with your data, I will take a look at their code what they have done
and try to apply that to our v3.6.2 copy.

Thanks,

Piyapong.

**Comment by johnhuck** [comment]
I loaded it up and the french text came in fine (in two ravens) - the
advanced options button had UTF-8 set as the as default

**Comment by piyapongch** [comment]
The feature has been implemented in Dataverse 4.0. We will upgrade to the new version in the near future.
