### ISSUE TITLE
[EZID] Handle Server Maintenance this Saturday, affects DOI service only

### ISSUE THREAD

**Issue by wyman10** [ualbertalib/dvn#27]
Can we have this downtime added to the UAL DNV homepage:

something like:

Between 8:00 AM & 10:00 AM on Saturday June 27th, 2015, it will not be possible to create any new DOIs.

---

“CNRI is going to move DataCite's primary handle server to another server rack. During the required downtime of the handle server no DOI minting via our MDS will be possible.

Neither DOI resolution our any other DataCite service will be affected; only DOI minting and updating will not work for a short period of time.

The server migration will start on 2015-06-27 at about 14:00 UTC and should not last for more than 2 hours.”

Here is a link you can use to determine the timing of the outage in your location:

http://www.timeanddate.com/worldclock/fixedtime.html?msg=Handle+Server+Maintenance&year=&month=06&day=27&hour=14&min=0&sec=0&p1=%3A&ah=2

We apologize for the late notice as well as the inconvenience. Please let us know if you have questions.

The EZID Team

**Comment by piyapongch** [comment]
I have tried to test it on the development server, but I could not. I have issue a ticket  to Henry to take a look. I will let you check it on the server when the message has changed.

**Comment by piyapongch** [comment]
I have changed the message on the development server, [https://hibernian.library.ualberta.ca/](https://hibernian.library.ualberta.ca/). Can you take a look?

**Comment by wyman10** [comment]
looks good!

**Comment by piyapongch** [comment]
The message is now on the production server.

**Comment by wyman10** [comment]
Please remove the message "Between 8:00 AM & 10:00 AM on Saturday June 27th, 2015, it will not be possible to create any new DOIs." on the UAL DV homepage.

**Comment by piyapongch** [comment]
I have removed the message.
