### ISSUE TITLE
User Can not Log in

### ISSUE THREAD

**Issue by wyman10** [ualbertalib/dvn#32]
A dataverse user has noted that they can not log in using their CCID. 

Checking into the issue I noticed that they have three active accounts all of which are based on their ualberta email and CCID username.

Username jie13
Full Name Jie Wang
E-Mail jie13@ualberta.ca

I checked the dataverse email account to see if they had tried to register as a guest (when people do this I email them directing them to use their CCID), however, they have not tried to register a guest account.

**Comment by piyapongch** [comment]
I will start to work on this issue.

**Comment by piyapongch** [comment]
I have checked the data. There are more than one duplicate usernames. Some of them have different  email addresses. I think it might happen when we have launched and had a training class. The earlier version did not have CCID login feature and might have had bug that allowed user to register with same username and email address.

Here are the duplicate usernames:
Ali,Shiri
Robyn,Stobbs
Bettina,Berendt
Jie,Wang

**Comment by piyapongch** [comment]
Larry:

I have found that the user jie13 is also has the same CCID, jie13. I have tested on the test server, hibernian and tried to create a new account using username jie13. The application returned back with error message, username already taken. 

I think we can fix the problem by rename the usernames to jie13_1,  jie13_2 and  jie13_3 and deactivate them. The user should be able to login again using CCID. What do you think?

**Comment by wyman10** [comment]
This sounds good to me!

**Comment by piyapongch** [comment]
I will work with Henry this afternoon. I will not delete any user data. They will be changed to other unique usernames and deactivated. We can recover them back if needed.

**Comment by piyapongch** [comment]
Henry is busy today. We will do it tomorrow morning after standup meeting.

**Comment by wyman10** [comment]
ok sounds good

**Comment by piyapongch** [comment]
I have renamed the duplicate usernames, jie13 to jie13_1, jie13_2 and jie13_3 and deactivated them.

I have seen a new username, jie13 was created when user has logged in using CCID. This should be working as expected.

**Comment by wyman10** [comment]
The jie13 user confirmed that they can now log in.

However, I got an email tonight from a user sulz (an HSS Librarian) saying
they could not log in. Checking the permissions user list they also have
two accounts under the same username - yet they were not on the duplicate
username list you sent me last week?

So somehow a second username was created (They told me they were using
dataverse fine during today and it was just in the last hour that they
could not log in.

This user does have a dataverse and a study so we have to be careful.

http://dx.doi.org/10.7939/DVN/10531

Larry

**Comment by piyapongch** [comment]
I will take a look at the problem tomorrow morning. Hopefully, the study associates with only one account. So, we can just rename the one that does not have study.

**Comment by piyapongch** [comment]
I have checked on the username sulz and rename the one that has id, 241 to sulz_1. The username does not have any study associate with it. I have also deactivated the username sulz_1.

The user should be able to login using ccid. Please let the user try again and let me know.

Thanks,

**Comment by wyman10** [comment]
He was able to login fine (case 2 of 2 closed)
