### ISSUE TITLE
New Dataverse extract (Sept 29)

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dvn#33]
Hello @piyapongch and @henryzhang87 .

Could you please prepare another extract of Dataverse metadata for me? Again, if you could separate the OAI-DC from the DDI files that would be ideal. For your reference, here's the issue from last time.

https://github.com/ualbertalib/dvn/issues/28

I plan to run the required transformation on the metadata extract later this week so it can be included in our ERA launch next week.

Thank you

**Comment by piyapongch** [comment]
I have export all the metadata. I will issue a ticket to Henry to the data from production server.

**Comment by piyapongch** [comment]
Done.
