### ISSUE TITLE
broken links on dataverse

### ISSUE THREAD

**Issue by wyman10** [ualbertalib/dvn#35]
The broken links found:
"contact us"
"data management @ uofa"

should be changed to
"contact us"
https://docs.google.com/a/ualberta.ca/forms/d/1kBbI52FTqG5fdTfaq_7NaddEFJGNyORvvYhxsP-9zHY/viewform?usp=send_form

"data management @ uofa"
https://www.library.ualberta.ca/research-support/data-management

**Comment by piyapongch** [comment]
I have changed the links. Can you check them on the test server at https://dataverse.library.ualberta.ca/dvn/ to make sure that they are point to the right pages?

**Comment by wyman10** [comment]
Can you send me the test server link?

**Comment by piyapongch** [comment]
Sorry, wrong one. Here is the test server link, https://hibernian.library.ualberta.ca/dvn/.

**Comment by wyman10** [comment]
They work!

thanks
Larry
