### ISSUE TITLE
Request for a new metadata export

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dvn#37]
@piyapongch I would like a new extract of metadata from Dataverse, please.

As we have discussed, an important step is to vacate the folder where the export will be saved so that we get updated files as well as new files.

Again, if possible, it would be convenient to get both the DC and DDI, but to have them saved in two separate folder hierarchies. I will be working with the DDI, but may wish to refer to the DC equivalents from time to time. Thank you!

**Comment by piyapongch** [comment]
I have shared the Dataverse DC and DDI metadata files on Google Drive. These package include all studies in the Dataverse.
