### ISSUE TITLE
Request for new metadata extract (Aug 2016)

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dvn#40]
@piyapongch , would you please get me a new extract of metadata from Dataverse.

As we have discussed in the past, an important step for Henry is to vacate the folder where the export will be saved so that we get updated files as well as new files.

Could I please have both the DC and DDI, but have them saved in two separate folder hierarchies? I will be working with the DDI, but may wish to refer to the DC equivalents from time to time. Thank you!

**Comment by pcharoen** [comment]
Here is the instruction to export DVN metadata.
https://docs.google.com/a/ualberta.ca/document/d/166T5FX6PhF3DehShUqteO_swOGI5fnQlGh975rl_btE/edit?usp=sharing

Henry:

Could you please export the data as requested? We have done this before.
Let me know if you have any question.

Thanks,

Piyapong.

**Comment by johnhuck** [comment]
@pcharoen, Thank you for the link. Actually, I found your instructions last week and @henryzhang87 and I were able to complete the export last week. I neglected to come back and update this ticket. My apologies! The instructions were very helpful. It was a good exercise for me.

**Comment by johnhuck** [comment]
Also, btw, I shared the instructions and the Google Drive folder where you have saved previous exports for me with Henry.
